services:
  - type: web
    name: pozivnice-backend
    env: node
    buildCommand: npm install && npx prisma generate && npx prisma db push
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: ADMIN_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
